### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.*.*/com.ixuea.android.downloader.DownloadService }: app is in background

### ISSUE THREAD

**Issue by rommansabbir** [lifengsofts/AndroidDownloader#45]
When app start, randomly I'm getting this error:

```kotlin
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.*.*/com.ixuea.android.downloader.DownloadService }: app is in background uid UidRecord{39694b8 u0a207 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
                        	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1795)
                        	at android.app.ContextImpl.startService(ContextImpl.java:1740)
                        	at android.content.ContextWrapper.startService(ContextWrapper.java:738)
                        	at com.ixuea.android.downloader.DownloadService.getDownloadManager(DownloadService.java:31)
                        	at com.ixuea.android.downloader.DownloadService.getDownloadManager(DownloadService.java:25)
                        	at com.*.APAppUpdater.init(APAppUpdater.kt:29)
                        	at com.*MyApp.onCreate(MyApp.kt:27)
                        	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
                        	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7527)
                        	at android.app.ActivityThread.access$1400(ActivityThread.java:301) 
                        	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2150) 
                        	at android.os.Handler.dispatchMessage(Handler.java:106) 
                        	at android.os.Looper.loop(Looper.java:246) 
                        	at android.app.ActivityThread.main(ActivityThread.java:8587) 
                        	at java.lang.reflect.Method.invoke(Native Method) 
                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

**Comment by dhs964057117** [comment]
> When app start, randomly I'm getting this error:
> 
> Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.*.*/com.ixuea.android.downloader.DownloadService }: app is in background uid UidRecord{39694b8 u0a207 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
>                         	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1795)
>                         	at android.app.ContextImpl.startService(ContextImpl.java:1740)
>                         	at android.content.ContextWrapper.startService(ContextWrapper.java:738)
>                         	at com.ixuea.android.downloader.DownloadService.getDownloadManager(DownloadService.java:31)
>                         	at com.ixuea.android.downloader.DownloadService.getDownloadManager(DownloadService.java:25)
>                         	at com.*.APAppUpdater.init(APAppUpdater.kt:29)
>                         	at com.*MyApp.onCreate(MyApp.kt:27)
>                         	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
>                         	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7527)
>                         	at android.app.ActivityThread.access$1400(ActivityThread.java:301) 
>                         	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2150) 
>                         	at android.os.Handler.dispatchMessage(Handler.java:106) 
>                         	at android.os.Looper.loop(Looper.java:246) 
>                         	at android.app.ActivityThread.main(ActivityThread.java:8587) 
>                         	at java.lang.reflect.Method.invoke(Native Method) 
>                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
>                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

This repository seems to be out of maintenance. I have a repository that is being maintained. Maybe you can try it?https://github.com/dhs964057117/Titan-Downloader
